apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: CHANNEL
  required: true
- name: IMAGE_TAG
  required: true
- name: IMAGE_DIGEST
  required: true
- name: NAMESPACE
  value: openshift-osd-example-operator
- name: REGISTRY_IMG
  required: true
- name: REPO_NAME
  value: osd-example-operator
  required: true
metadata:
  name: selectorsyncset-template
objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    labels:
      managed.openshift.io/gitHash: ${IMAGE_TAG}
      managed.openshift.io/gitRepoName: osd-example-operator
      managed.openshift.io/osd: 'true'
    name: osd-example-operator
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/name: osde2e-example-1
    resourceApplyMode: Upsert
    resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          openshift.io/cluster-monitoring: 'true'
        name: osd-example-operator
    - apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: osd-example-operator
        namespace: osd-example-operator
        annotations:
          olm.operatorframework.io/exclude-global-namespace-resolution: 'true'
      spec:
        targetNamespaces:
        - e2e-testing
    - apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        labels:
          opsrc-datastore: 'true'
          opsrc-provider: redhat
        name: osd-example-operator-registry
        namespace: osd-example-operator
      spec:
        displayName: osd-example-operator
        icon:
          base64data: ''
          mediatype: ''
        image: quay.io/app-sre/osd-example-operator-registry@sha256:d5b2c635773a6f9ce5901ca6414eeaca832575ece5de64028c9b4b00ba870110
        publisher: Red Hat
        sourceType: grpc
        grpcPodConfig:
          securityContextConfig: restricted
          nodeSelector:
            node-role.kubernetes.io: infra
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/infra
            operator: Exists
    - apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: osd-example-operator
        namespace: osd-example-operator
      spec:
        channel: staging
        name: osd-example-operator
        source: osd-example-operator-registry
        sourceNamespace: osd-example-operator
