apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: managed-release-bundle-gate-job-template
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: managed-release-bundle-gate
  spec:
    template:
      spec:
        containers:
        - name: test
          image: ubi8/ubi-minimal:latest
          command: ["sh", "-c", "exit 0"]
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
        restartPolicy: Never
