apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: IMAGE_TAG
  required: true
- name: IMAGE_NAME
  value: quay.io/app-sre/managed-release-bundle
- name: OPENSHIFT_MAJOR_MINOR_VERSION
  value: "4.16"
metadata:
  name: selectorsyncset-template
objects:
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: release-bundle-config-${OPENSHIFT_MAJOR_MINOR_VERSION}
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
      matchExpressions:
        - key: hive.openshift.io/version-major-minor
          operator: In
          values:
            - "${OPENSHIFT_MAJOR_MINOR_VERSION}"
    resourceApplyMode: Sync
    enableResourceTemplates: true
    resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: osd-cluster-metadata
        namespace: openshift-config
      data:
        api.openshift.com_name: "{{ fromCDLabel \"api.openshift.com/name\" }}"
        api.openshift.com_product: "{{ fromCDLabel \"api.openshift.com/product\" }}"
        api.openshift.com_fedramp: "{{ fromCDLabel \"api.openshift.com/fedramp\" }}"
        api.openshift.com_sts: "{{ fromCDLabel \"api.openshift.com/sts\" }}"
        api.openshift.com_limited-support: "{{ fromCDLabel \"api.openshift.com/limited-support\" }}"
        api.openshift.com_private-link: "{{ fromCDLabel \"api.openshift.com/private-link\" }}"
        api.openshift.com_ccs: "{{ fromCDLabel \"api.openshift.com/ccs\" }}"
        api.openshift.com_channel-group: "{{ fromCDLabel \"api.openshift.com/channel-group\" }}"
        api.openshift.com_environment: "{{ fromCDLabel \"api.openshift.com/environment\" }}"
        hive.openshift.io_cluster-platform: "{{ fromCDLabel \"hive.openshift.io/cluster-platform\" }}"
        hive.openshift.io_cluster-region: "{{ fromCDLabel \"hive.openshift.io/cluster-region\" }}"
- apiVersion: hive.openshift.io/v1
  kind: SelectorSyncSet
  metadata:
    name: release-bundle-${OPENSHIFT_MAJOR_MINOR_VERSION}
  spec:
    clusterDeploymentSelector:
      matchLabels:
        api.openshift.com/managed: 'true'
      matchExpressions:
        - key: hive.openshift.io/version-major-minor
          operator: In
          values:
            - "${OPENSHIFT_MAJOR_MINOR_VERSION}"
    resourceApplyMode: Sync
    resources:
    - apiVersion: package-operator.run/v1alpha1
      kind: ClusterObjectTemplate
      metadata:
        name: managed-release-bundle-template
      spec:
        sources:
        - apiVersion: v1
          items:
          - destination: .
            key: .data
          kind: ConfigMap
          name: osd-cluster-metadata
          namespace: openshift-config
          optional: true
        template: |
          apiVersion: package-operator.run/v1alpha1
          kind: ClusterPackage
          metadata:
            name: managed-release-bundle
          spec:
            image: ${IMAGE_NAME}:${OPENSHIFT_MAJOR_MINOR_VERSION}-${IMAGE_TAG}
            config: {{toJson .config}}
